### ISSUE TITLE
Old react-native version!

### ISSUE THREAD

**Issue by kiranraj2k** [algolia/hn-reactnative-sample#3]
Is it possible to update this project with the latest version of react-native?

**Comment by bobylito** [comment]
I merged an old PR that was already upgrading the project. Will spend some time checking it. On the other hand we are close to releasing a new version of instantsearch that will work with react-native. I'll update it after the release, but you can have a look at the [project website](https://community.algolia.com/instantsearch.js/react/) in the time being.
